# Generated by Django 4.1.1 on 2022-10-04 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TechnologiesUsed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technology', models.CharField(choices=[('Figma', 'Figma'), ('React', 'React'), ('Django', 'Django')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('With live view', 'With live view'), ('Design presentation', 'Design presentation')], max_length=255)),
                ('type', models.CharField(choices=[('Website WWW', 'Website WWW')], max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('technologies', models.ManyToManyField(to='Projects.technologiesused')),
            ],
        ),
    ]
