# Generated by Django 4.0.4 on 2022-10-04 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0004_remove_technologiesused_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='technologiesused',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='technologiesused',
            name='technology',
            field=models.CharField(choices=[('Figma', 'Figma'), ('React', 'React'), ('Django', 'Django')], max_length=255),
        ),
    ]
