# Generated by Django 4.0.4 on 2022-10-04 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0005_technologiesused_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technologiesused',
            name='id',
        ),
        migrations.AlterField(
            model_name='technologiesused',
            name='technology',
            field=models.CharField(choices=[('Figma', 'Figma'), ('React', 'React'), ('Django', 'Django')], max_length=255, primary_key=True, serialize=False),
        ),
    ]
